const NOMBRES_EN_ESPANOL_POR_CODIGO: Record<string, string> = {
  ARG: "Argentina",
  BRA: "Brasil",
  URU: "Uruguay",
  PAR: "Paraguay",
  CHI: "Chile",
  BOL: "Bolivia",
  PER: "Perú",
  ECU: "Ecuador",
  COL: "Colombia",
  VEN: "Venezuela",
  MEX: "México",
  USA: "Estados Unidos",
  CAN: "Canadá",
  CRC: "Costa Rica",
  PAN: "Panamá",
  HON: "Honduras",
  SLV: "El Salvador",
  GUA: "Guatemala",
  JAM: "Jamaica",
  HAI: "Haití",
  DOM: "República Dominicana",
  CUB: "Cuba",
  ESP: "España",
  FRA: "Francia",
  GER: "Alemania",
  ITA: "Italia",
  POR: "Portugal",
  ENG: "Inglaterra",
  SCO: "Escocia",
  WAL: "Gales",
  NED: "Países Bajos",
  BEL: "Bélgica",
  CRO: "Croacia",
  SRB: "Serbia",
  BIH: "Bosnia y Herzegovina",
  SUI: "Suiza",
  AUT: "Austria",
  POL: "Polonia",
  CZE: "República Checa",
  SVK: "Eslovaquia",
  SVN: "Eslovenia",
  HUN: "Hungría",
  ROU: "Rumania",
  BUL: "Bulgaria",
  UKR: "Ucrania",
  GRE: "Grecia",
  TUR: "Turquía",
  DEN: "Dinamarca",
  SWE: "Suecia",
  NOR: "Noruega",
  FIN: "Finlandia",
  ISL: "Islandia",
  IRL: "Irlanda",
  NIR: "Irlanda del Norte",
  RUS: "Rusia",
  GEO: "Georgia",
  ALB: "Albania",
  MKD: "Macedonia del Norte",
  MNE: "Montenegro",
  KOS: "Kosovo",
  LTU: "Lituania",
  LVA: "Letonia",
  EST: "Estonia",
  BLR: "Bielorrusia",
  LUX: "Luxemburgo",
  CYP: "Chipre",
  MLT: "Malta",
  AND: "Andorra",
  SMR: "San Marino",
  AZE: "Azerbaiyán",
  ARM: "Armenia",
  KAZ: "Kazajistán",
  MDA: "Moldavia",
  AFG: "Afganistán",
  KSA: "Arabia Saudita",
  QAT: "Catar",
  UAE: "Emiratos Árabes Unidos",
  IRQ: "Irak",
  IRN: "Irán",
  ISR: "Israel",
  JOR: "Jordania",
  KUW: "Kuwait",
  LBN: "Líbano",
  OMA: "Omán",
  PLE: "Palestina",
  SYR: "Siria",
  YEM: "Yemen",
  AUS: "Australia",
  NZL: "Nueva Zelanda",
  JPN: "Japón",
  KOR: "Corea del Sur",
  PRK: "Corea del Norte",
  CHN: "China",
  TPE: "Taipéi Chino",
  HKG: "Hong Kong",
  IND: "India",
  IDN: "Indonesia",
  THA: "Tailandia",
  VIE: "Vietnam",
  MAS: "Malasia",
  SIN: "Singapur",
  PHI: "Filipinas",
  UZB: "Uzbekistán",
  TJK: "Tayikistán",
  TKM: "Turkmenistán",
  KGZ: "Kirguistán",
  MNG: "Mongolia",
  NPL: "Nepal",
  PAK: "Pakistán",
  BAN: "Bangladés",
  SRI: "Sri Lanka",
  RSA: "Sudáfrica",
  MAR: "Marruecos",
  ALG: "Argelia",
  TUN: "Túnez",
  EGY: "Egipto",
  NGA: "Nigeria",
  GHA: "Ghana",
  CIV: "Costa de Marfil",
  CMR: "Camerún",
  SEN: "Senegal",
  MLI: "Malí",
  BFA: "Burkina Faso",
  COD: "República Democrática del Congo",
  CGO: "Congo",
  GAB: "Gabón",
  GUI: "Guinea",
  GEQ: "Guinea Ecuatorial",
  BEN: "Benín",
  TOG: "Togo",
  UGA: "Uganda",
  KEN: "Kenia",
  ZAM: "Zambia",
  ZIM: "Zimbabue",
  MOZ: "Mozambique",
  ANG: "Angola",
  BOT: "Botsuana",
  CPV: "Cabo Verde",
  MTN: "Mauritania",
  LBY: "Libia",
  SDN: "Sudán",
  TAN: "Tanzania",
};

const NOMBRES_EN_ESPANOL_POR_INGLES: Record<string, string> = {
  argentina: "Argentina",
  brazil: "Brasil",
  uruguay: "Uruguay",
  paraguay: "Paraguay",
  chile: "Chile",
  bolivia: "Bolivia",
  peru: "Perú",
  ecuador: "Ecuador",
  colombia: "Colombia",
  venezuela: "Venezuela",
  mexico: "México",
  "united states": "Estados Unidos",
  canada: "Canadá",
  "costa rica": "Costa Rica",
  panama: "Panamá",
  honduras: "Honduras",
  "el salvador": "El Salvador",
  guatemala: "Guatemala",
  jamaica: "Jamaica",
  haiti: "Haití",
  "dominican republic": "República Dominicana",
  cuba: "Cuba",
  spain: "España",
  france: "Francia",
  germany: "Alemania",
  italy: "Italia",
  portugal: "Portugal",
  england: "Inglaterra",
  scotland: "Escocia",
  wales: "Gales",
  netherlands: "Países Bajos",
  belgium: "Bélgica",
  croatia: "Croacia",
  serbia: "Serbia",
  "bosnia and herzegovina": "Bosnia y Herzegovina",
  switzerland: "Suiza",
  austria: "Austria",
  poland: "Polonia",
  "czech republic": "República Checa",
  czechia: "República Checa",
  slovakia: "Eslovaquia",
  slovenia: "Eslovenia",
  hungary: "Hungría",
  romania: "Rumania",
  bulgaria: "Bulgaria",
  ukraine: "Ucrania",
  greece: "Grecia",
  turkey: "Turquía",
  denmark: "Dinamarca",
  sweden: "Suecia",
  norway: "Noruega",
  finland: "Finlandia",
  iceland: "Islandia",
  ireland: "Irlanda",
  "northern ireland": "Irlanda del Norte",
  russia: "Rusia",
  georgia: "Georgia",
  albania: "Albania",
  "north macedonia": "Macedonia del Norte",
  montenegro: "Montenegro",
  kosovo: "Kosovo",
  lithuania: "Lituania",
  latvia: "Letonia",
  estonia: "Estonia",
  belarus: "Bielorrusia",
  luxembourg: "Luxemburgo",
  cyprus: "Chipre",
  malta: "Malta",
  andorra: "Andorra",
  "san marino": "San Marino",
  azerbaijan: "Azerbaiyán",
  armenia: "Armenia",
  kazakhstan: "Kazajistán",
  moldova: "Moldavia",
  afghanistan: "Afganistán",
  "saudi arabia": "Arabia Saudita",
  qatar: "Catar",
  "united arab emirates": "Emiratos Árabes Unidos",
  iraq: "Irak",
  iran: "Irán",
  israel: "Israel",
  jordan: "Jordania",
  kuwait: "Kuwait",
  lebanon: "Líbano",
  oman: "Omán",
  palestine: "Palestina",
  syria: "Siria",
  yemen: "Yemen",
  australia: "Australia",
  "new zealand": "Nueva Zelanda",
  japan: "Japón",
  "south korea": "Corea del Sur",
  "north korea": "Corea del Norte",
  china: "China",
  india: "India",
  indonesia: "Indonesia",
  thailand: "Tailandia",
  vietnam: "Vietnam",
  malaysia: "Malasia",
  singapore: "Singapur",
  philippines: "Filipinas",
  uzbekistan: "Uzbekistán",
  tajikistan: "Tayikistán",
  turkmenistan: "Turkmenistán",
  kyrgyzstan: "Kirguistán",
  mongolia: "Mongolia",
  nepal: "Nepal",
  pakistan: "Pakistán",
  bangladesh: "Bangladés",
  "sri lanka": "Sri Lanka",
  "south africa": "Sudáfrica",
  morocco: "Marruecos",
  algeria: "Argelia",
  tunisia: "Túnez",
  egypt: "Egipto",
  nigeria: "Nigeria",
  ghana: "Ghana",
  "ivory coast": "Costa de Marfil",
  cameroon: "Camerún",
  senegal: "Senegal",
  mali: "Malí",
  "burkina faso": "Burkina Faso",
  "dr congo": "República Democrática del Congo",
  "congo dr": "República Democrática del Congo",
  congo: "Congo",
  gabon: "Gabón",
  guinea: "Guinea",
  "equatorial guinea": "Guinea Ecuatorial",
  benin: "Benín",
  togo: "Togo",
  uganda: "Uganda",
  kenya: "Kenia",
  zambia: "Zambia",
  zimbabwe: "Zimbabue",
  mozambique: "Mozambique",
  angola: "Angola",
  botswana: "Botsuana",
  "cape verde": "Cabo Verde",
  mauritania: "Mauritania",
  libya: "Libia",
  sudan: "Sudán",
  tanzania: "Tanzania",
};

function normalizeCountryName(value?: string | null) {
  return (value ?? "")
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
    .trim();
}

export function getNombreSeleccionEnEspanol(params: {
  codigo?: string | null;
  nombre?: string | null;
}) {
  const codigo = params.codigo?.trim().toUpperCase();

  if (codigo && NOMBRES_EN_ESPANOL_POR_CODIGO[codigo]) {
    return NOMBRES_EN_ESPANOL_POR_CODIGO[codigo];
  }

  const nombreNormalizado = normalizeCountryName(params.nombre);

  if (nombreNormalizado && NOMBRES_EN_ESPANOL_POR_INGLES[nombreNormalizado]) {
    return NOMBRES_EN_ESPANOL_POR_INGLES[nombreNormalizado];
  }

  return params.nombre?.trim() ?? "";
}
